/** 화면 문구는 전부 여기 (plan.md §10 — 하드코딩 금지) */
export const COPY = {
  siteTitle: 'ENSIL — Electronic Ensilage',
  systemTitle: 'Electronic Ensilage',
  physicalWaiting: '◍ 물리연동 대기',
  physicalConnected: '◍ 물리연동 연결됨',
  physicalLost: '◍ 물리연동 끊김',
  syncLocal: '데이터: 로컬본',
  modeSpecimen: '표본',
  modeSim: '시뮬레이션',
  about: '소개',
  aboutTitle: '발효된 전자 생명의 탄생',
  aboutClose: '닫기',
  overviewTitle: '전자 생명을 관찰하세요',
  overviewHint: '상단 인덱스에서 표본을 선택해 감각 입력과 행동 출력을 추적하세요.',
  taxonPanel: '▸ 계통',
  taxonRoot: '전자생물',
  purposePanel: '▸ 최초의 목적',
  notesPanel: '▸ 관찰 기록',
  traitCharge: '전하',
  traitStimulus: '자극',
  traitBond: '결속',
  needEnergy: '에너지',
  needArousal: '자극',
  needBonding: '결속',
  simStatePrefix: '상태',
  simPurposePrefix: '목적',
  simGotoSpecimen: '표본 보기 ›',
  simCount: '개체',
  simPaused: '일시정지됨',
  registered: '등재',
  statusLabel: '상태',
  visualPlaceholder: 'LIVE SPECIMEN / SIGNAL FEED',
  diagramPlaceholder: 'INPUT → METABOLISM → BEHAVIOR → MEMORY',
  galleryTitle: '전자생물 아카이브',
  galleryHint: '( 개체를 눌러 표본을 열람하세요 )',
} as const;

export const TAXON_NAME: Record<string, string> = {
  A: '계통 A',
  B: '계통 B',
  C: '계통 C',
};

export const SIM_STATE_NAME: Record<string, string> = {
  idle: '대기',
  seek: '탐색',
  consume: '섭취',
  rest: '휴식',
  interact: '접촉',
};
